# Generated by Django 2.2.7 on 2019-11-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengguna', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('no_hp', models.IntegerField()),
                ('foto', models.ImageField(blank=True, upload_to='gambar/%Y/%m/%d/')),
                ('deskriptsi', models.TextField(blank=True)),
                ('tanggal_bergabung', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
