# Generated by Django 2.2.7 on 2019-11-20 17:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jualan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_item', models.CharField(max_length=200)),
                ('alamat', models.CharField(max_length=200)),
                ('no_hp', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('nama', models.CharField(max_length=200)),
                ('jumlah_kartu', models.IntegerField()),
                ('harga', models.IntegerField()),
                ('is_published', models.BooleanField(default=True)),
                ('tanggal', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('gambar', models.ImageField(upload_to='gambar/%Y/%m/%d/')),
                ('gambar_1', models.ImageField(blank=True, upload_to='gambar/%Y/%m/%d/')),
                ('gambar_2', models.ImageField(blank=True, upload_to='gambar/%Y/%m/%d/')),
                ('gambar_3', models.ImageField(blank=True, upload_to='gambar/%Y/%m/%d/')),
                ('gambar_4', models.ImageField(blank=True, upload_to='gambar/%Y/%m/%d/')),
                ('gambar_5', models.ImageField(blank=True, upload_to='gambar/%Y/%m/%d/')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pengguna.Pengguna')),
            ],
        ),
    ]
